Base64IO: set write buffer before doing attr check
TestBase64IO.test_init_fails() fails in current Fedora Rawhide
(with Python 3.13) because pytest complains about an unraisable
exception:

AttributeError: 'Base64IO' object has no attribute '_Base64IO__write_buffer'

it seems like we're reaching `close()` (via `__exit__()`, I
guess) even after raising an exception in `__init__()`, and that
causes a problem because we never set `self.__write_buffer` if
the required attrs check fails.

To solve this, we can just set `self.__write_buffer` before doing
the attr check.

Signed-off-by: Adam Williamson <awilliam@redhat.com>